deployment:
  backend:
    imageURL: "376159574294.dkr.ecr.us-east-1.amazonaws.com/expense-backend"
    imageVersion: "26"
    replicaCount: 2
  frontend:
    imageURL: "376159574294.dkr.ecr.us-east-1.amazonaws.com/expense-frontend"
    imageVersion: "26"
    replicaCount: 2