# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# nodes:
#   - role: control-plane
#     extraPortMappings:
#       - containerPort: 30080
#         hostPort: 30080
#         protocol: TCP
#

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1

iam:
  withOIDC: true

managedNodeGroups:
  - name: expense
    instanceTypes:
      - t3.medium
      - t3a.medium

    desiredCapacity: 2
    minSize: 2
    maxSize: 3

    spot: true

    volumeSize: 20
    volumeType: gp3

    labels:
      project: expense
      role: worker