[mysql]
mysql.devopswithravi.online

[backend]
backend.devopswithravi.online

[frontend]
frontend.devopswithravi.online

[local]
localhost

[all:vars]
ansible_password=DevOps321
#ansible_user=ec2-user

[nginx]
172.31.21.93