[mysql]
mysql.daws81s.online

[backend]
backend.daws81s.online

[frontend]
frontend.daws81s.online

[local]
localhost

[all:vars]
ansible_password=DevOps321
#ansible_user=ec2-user

[nginx]
172.31.21.93